services:
  db:
    image: postgres:15
    env_file: apps/back/.env
    ports:
      - '${DB_OUTER_PORT:-5433}:5432'
    volumes:
      - pararara:/var/lib/postgresql/data

  backend:
    build: ./apps/back
    env_file: ./apps/back/.env
    ports:
      - '${PORT:-8080}:8080'
    volumes:
      - ./apps/back:/app
      - /app/node_modules
      - /app/generated
    depends_on:
      - db

  frontend:
    build: ./apps/front
    env_file: ./apps/front/.env
    ports:
      - '${VITE_OUTER_PORT:-8000}:5173'
    volumes:
      - ./apps/front:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  pararara:
