services:
  db:
    image: postgres:15
    env_file: apps/back/.env
    ports:
      - '5433:5432'
    volumes:
      - pararara:/var/lib/postgresql/data

  backend:
    build: ./apps/back
    env_file: ./apps/back/.env
    ports:
      - '8080:8080'
    volumes:
      - ./apps/back:/app
      - /app/node_modules
    depends_on:
      - db

  frontend:
    build: ./apps/front
    env_file: ./apps/front/.env
    ports:
      - '5173:5173'
    volumes:
      - ./apps/front:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  pararara:
